import Wrapper from '@/components/shared/Wrapper'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/views/Navbar'
import Footer from '@/components/views/Footter'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
     
      {/* <body className="backdrop-blur-lg bg-gray-100 z-50"> */}
       
          <body className=" bg-white z-50 backdrop-blur-sm">
            <Navbar/>
        <Wrapper>
          {children}
         </Wrapper>
         <Footer/>
          
         
        </body>
    </html>
  )
}
